name: FlowerPower
author: NCBPFluffyBear
description: A flower-powered magic addon maintained for Slimefun Legacy
main: io.ncbpfluffybear.flowerpower.FlowerPowerPlugin
website: https://github.com/wickidcow/SF_FlowerPower
version: ${project.version}
api-version: '1.21'
depend:
  - Slimefun
